### ISSUE TITLE
Show "lead in item/page" (type "display") prior to each Questionnaire

### ISSUE THREAD

**Issue by mcjustin** [uwcirg/asbi-screening-app#42]
Add a “lead in page” to each questionnaire with the contents of Questionnaire.description, and perhaps some text around it eg:

"The next set of questions is the PHQ-9, a depression screener".
That might be populated by "The next set of questions is the " + Questionnaire.description.
If the Questionnaire doesn't have the "description" field populated, then don't show this.

For now, have a config in the screener that dictates whether to show it for all questionnaires. We may want to make this more conditional later, eg only include it if the user is a clinician.

**Comment by mcjustin** [comment]
@sierramatice  per our convo w/ Emily today

**Comment by mcjustin** [comment]
@achen2401  I can start to populating some Questionnaire.description fields.

**Comment by mcjustin** [comment]
@achen2401  please aim to have a first version of this implemented in a couple weeks (Nov 1)

**Comment by mcjustin** [comment]
> @mcjustin will it be okay to just have an introduction page containing the description in each questionnaire, like, for instance, [here](https://github.com/uwcirg/asbi-screening-app/blob/f90511755ff97dabd0f31e31d17e071f4e142975/src/fhir/1_Questionnaire-USAUDIT.json#L24)? That is easier, without any added logic to present needed.

@achen2401  That's probably a fine approach, just one I wasn't aware of. I see that they're using Questionnaire.item with type "display" https://www.hl7.org/fhir/valueset-item-type.html#expansion . I just had a look at the Structured Data Capture IG's section on rendering, but it doesn't really have anything to say about this (the closest thing is perhaps "supportLink" https://hl7.org/fhir/uv/sdc/rendering.html#additional-display-content ).

**Comment by achen2401** [comment]
@sierramatice Will you be able to provide introduction description for each questionnaire?  It is not clear to me from looking at the documentation, https://uwnetid.sharepoint.com/:w:/s/og_sadakresearch/EdDB0d-MUyBKtAVzaFGj5REB4LahDiwsKA65soXUJBK55Q?e=nvEMff,  what that should be for each?

**Comment by mcjustin** [comment]
@achen2401  if @sierramatice  wanted to include some simple html tags, is that okay? Can you please add a sample item/page to a new PR using a pattern that she can follow?

**Comment by sierramatice** [comment]
@achen2401 I believe I have added intros to all of the assessments!

**Comment by achen2401** [comment]
@sierramatice I added some comments in the [PR](https://github.com/uwcirg/asbi-screening-app/pull/47)  Just some minor issues that I think would be good to address.
