### ISSUE TITLE
Make radio buttons deselectable

### ISSUE THREAD

**Issue by mcjustin** [uwcirg/asbi-screening-app#45]
The system does not let the user deselect radio buttons, unlike our dhair and dhair2 systems, and other systems eg RedCAP.

If there's a global config for this somewhere, please change it. 

If it can be configured at a finer level, eg per instance or questionnaire, let's save that for a later discussion / issue.

**Comment by mcjustin** [comment]
Per @achen2401  today Not currently available in the survey js (a clear button is an option, but not ideal)

**Comment by achen2401** [comment]
@mcjustin Here is the thread where they discussed allowing user to de-select a radio button:

https://github.com/surveyjs/survey-library/issues/1176

**Comment by mcjustin** [comment]
@achen2401 @sierramatice  As I review RedCAP, I see that they have a similar approach to survey.js - note the "reset" link at lower left. 

@achen2401  can you please try enabling the equivalent survey.js feature, and let's see if it's tractable.

![image](https://user-images.githubusercontent.com/1036500/198110591-20c76657-df8f-4cad-a2e0-cdc7776e412a.png)

**Comment by achen2401** [comment]
@mcjustin & @sierramatice Please see https://github.com/uwcirg/asbi-screening-app/pull/51
