### ISSUE TITLE
2022-11-21: some questionnaires have empty questions

### ISSUE THREAD

**Issue by mcjustin** [uwcirg/asbi-screening-app#62]
SLUMS - entirely empty, one page w/out a question, and a submit button.

BEHAV5+ "Other behaviors" is empty: 
![image](https://user-images.githubusercontent.com/1036500/203202718-cdaba9f6-604c-42d4-8a22-6981870dbaec.png)

**Comment by achen2401** [comment]
@mcjustin for SLUMS, there is only one question - for staff to record score.  See [convo](https://github.com/uwcirg/asbi-screening-app/issues/34#issuecomment-1279591257) I had with Sie-ce about that.   And for Behav5,  there is a text field for the other behaviors. (You should be able to type on the line under the, other behaviors, text.)    I can see how it looks to be an empty page though.  I will see if I can fix the styling to make it obvious that there is an editable text field on the page, e.g. auto-focus on it.

**Comment by mcjustin** [comment]
Thanks @achen2401  yes, now that I try again I can see that I can enter a text response there. Yes, more of a cue would be good for this type of question. 

Also, I see a range of 0-30 for the [SLUMS](https://drive.google.com/file/d/1SemRdSK3QA58RMmfNRZAoAn9h1UY0Wvu/view?usp=sharing). I think we should indicate this in the questionnaire, and ideally restrict the possible values to 0-30. 
Thoughts about this change to SLUMS @sierramatice ?

**Comment by achen2401** [comment]
@mcjustin Sorry you didn’t get to review this but  I did implement validation for SLUMS [here](https://github.com/uwcirg/asbi-screening-app/pull/56) which Sie-ce approved.  You should only be able to enter a value between 0 y 30.
